version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.15.4 # the primary container, where your job's commands are run

    steps:
      - checkout # check out the code in the project directory
      - run: npm install
      - save-cache:
        key: v1-api-token-{{ .Branch }}-{{ checksum "config.js" }}
        paths:
          - /config.js
  test:
    docker:
      - image: cimg/node:14.15.4

    steps:
      - checkout
      - run: npm install
      - run: npm test -- --coverage

workflows:
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          jobs:
            - build